services:
  community_api:
    image: villabos/community-service:v1
    container_name: community_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

networks:
  default:
    name: proycloud_net
